import { BuddyRoom } from './types';

export const buddyRooms: BuddyRoom[] = [
  {
    id: 'room-vintage-tone',
    slug: 'vintage-tone-nerds',
    name: 'Vintage Tone & Tube Amps',
    description: 'A cozy sanctuary for overdrive pedals, tube amp bias talk, chord melody clips, and fretboard experiments.',
    hobbyId: 'hobby-guitar',
    hobbyName: 'Electric Guitar & Tone',
    icon: 'Guitar',
    coverImage: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1000&q=80',
    memberCount: 142,
    onlineCount: 28,
    tags: ['Pedalboards', 'Tube Amps', 'Neo-Soul Riffs', 'Jam Room'],
    pinnedAnnouncement: '📌 Weekly Jam Challenge: Post a 30s video using only 2 chord voicings with space and dynamics! Tag #LessIsMore.',
    lastMessageSnippet: 'Anyone tried running a Klon-style drive into a cranked Deluxe Reverb?',
    lastMessageTime: '3m ago',
    members: [
      {
        id: 'user-alex',
        name: 'Alex Rivera',
        avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
        role: 'mod',
        status: 'online',
        specialty: 'Stratocaster & Tube Gear',
      },
      {
        id: 'user-saif',
        name: 'Saif B. (You)',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
        role: 'member',
        status: 'online',
        specialty: 'Neo-Soul Chords',
      },
      {
        id: 'inst-marcus-vance',
        name: 'Marcus Vance',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
        role: 'mentor',
        status: 'idle',
        specialty: 'Touring Guitar Mentor',
      },
      {
        id: 'user-chloe',
        name: 'Chloe Adams',
        avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
        role: 'member',
        status: 'offline',
        specialty: 'Acoustic fingerstyle',
      },
    ],
  },
  {
    id: 'room-aeropress',
    slug: 'pourover-and-dialin',
    name: 'Pour-Over Dial-In & Roast Nerds',
    description: 'Grind size charts, water TDS mineral recipes, V60 drawdown troubleshooting, and rare natural coffee bean shares.',
    hobbyId: 'hobby-coffee',
    hobbyName: 'Specialty Coffee Brewing',
    icon: 'Coffee',
    coverImage: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1000&q=80',
    memberCount: 98,
    onlineCount: 19,
    tags: ['V60', 'Aeropress', 'TDS & Extraction', 'Water Chemistry'],
    pinnedAnnouncement: '📌 Roaster of the Month: We are testing the anaerobic Colombian Pink Bourbon from Roam Roasters this week!',
    lastMessageSnippet: 'Try 91°C water with 50ppm hardness, the floral jasmine notes explode.',
    lastMessageTime: '12m ago',
    members: [
      {
        id: 'user-chloe',
        name: 'Chloe Adams',
        avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
        role: 'mod',
        status: 'online',
        specialty: 'Sensory & Dial-in',
      },
      {
        id: 'inst-elena-rostova',
        name: 'Elena Rostova',
        avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
        role: 'mentor',
        status: 'online',
        specialty: 'Q-Grader Instructor',
      },
      {
        id: 'user-saif',
        name: 'Saif B. (You)',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
        role: 'member',
        status: 'online',
        specialty: 'V60 Brewer',
      },
    ],
  },
  {
    id: 'room-leica-street',
    slug: 'street-photography-grain',
    name: '35mm Film & Street Snaps',
    description: 'Urban perspectives, golden hour reflections, monochrome street candids, and contact sheet reviews.',
    hobbyId: 'hobby-photo',
    hobbyName: 'Street & Analog Photography',
    icon: 'Camera',
    coverImage: 'https://images.unsplash.com/photo-1493863641943-9b68992a8d07?auto=format&fit=crop&w=1000&q=80',
    memberCount: 215,
    onlineCount: 42,
    tags: ['35mm Film', 'Street Candids', 'Monochrome', 'Critique Room'],
    pinnedAnnouncement: '📌 Photo Walk Theme: "Reflections in Puddles and Store Windows". Post your 1 favorite frame by Sunday midnight.',
    lastMessageSnippet: 'Shot on HP5 pushed to 800 in Shinjuku during drizzle. The grain has so much soul.',
    lastMessageTime: '24m ago',
    members: [
      {
        id: 'user-jin',
        name: 'Jin Woo',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
        role: 'mod',
        status: 'online',
        specialty: 'B&W Film',
      },
      {
        id: 'inst-kai-takahashi',
        name: 'Kai Takahashi',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
        role: 'mentor',
        status: 'idle',
        specialty: 'Leica Documentary Mentor',
      },
      {
        id: 'user-saif',
        name: 'Saif B. (You)',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
        role: 'member',
        status: 'online',
        specialty: 'Street Frames',
      },
    ],
  },
  {
    id: 'room-ceramic-wheel',
    slug: 'wheel-throwing-and-glazing',
    name: 'Clay Studio & Glaze Chemistry',
    description: 'Show your freshly thrown mugs, trimmed foot rings, glaze test tiles, and celebrate kiln opening days!',
    hobbyId: 'hobby-pottery',
    hobbyName: 'Studio Ceramic & Pottery',
    icon: 'Sparkles',
    coverImage: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1000&q=80',
    memberCount: 76,
    onlineCount: 14,
    tags: ['Pottery Wheel', 'Glaze Recipes', 'Trimming', 'Kiln Firing'],
    pinnedAnnouncement: '📌 Glaze Safety: Always wear your N95 respirator when mixing dry silica & cobalt powders.',
    lastMessageSnippet: 'Finally centered 2.5kg of stoneware without throwing my lower back out!',
    lastMessageTime: '1h ago',
    members: [
      {
        id: 'user-maya',
        name: 'Maya Lin',
        avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
        role: 'member',
        status: 'online',
        specialty: 'Stoneware & Bowls',
      },
      {
        id: 'inst-clara-chen',
        name: 'Clara Chen',
        avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
        role: 'mentor',
        status: 'offline',
        specialty: 'High-fire Reduction Ceramics',
      },
    ],
  },
  {
    id: 'room-procreate-art',
    slug: 'procreate-and-concept-art',
    name: 'Stylized Art & Character Design',
    description: 'Share your WIP speedpaints, color thumbnails, brush sets, and get constructive feedback on silhouettes and lighting.',
    hobbyId: 'hobby-digital-art',
    hobbyName: 'Digital Art & Concept Design',
    icon: 'Palette',
    coverImage: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1000&q=80',
    memberCount: 184,
    onlineCount: 37,
    tags: ['Procreate', 'Character Concepts', 'Speedpaint', 'Critique'],
    pinnedAnnouncement: '📌 Daily Prompt: Cyberpunk street food vendor in an alleyway. Keep thumbnails under 15 minutes!',
    lastMessageSnippet: 'Loving the bounce light on the jacket edge in that concept piece.',
    lastMessageTime: '45m ago',
    members: [
      {
        id: 'user-maya',
        name: 'Maya Lin',
        avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
        role: 'mod',
        status: 'online',
        specialty: 'Stylized Illustration',
      },
      {
        id: 'inst-sora-matsuda',
        name: 'Sora Matsuda',
        avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=300&q=80',
        role: 'mentor',
        status: 'online',
        specialty: 'Lead Concept Mentor',
      },
    ],
  },
  {
    id: 'room-japan-joinery',
    slug: 'japanese-joinery-craft',
    name: 'Japanese Woodcraft & Chisels',
    description: 'The pursuit of razor-sharp shavings, kumiko lattices, and joint alignment without mechanical fasteners.',
    hobbyId: 'hobby-woodwork',
    hobbyName: 'Japanese Joinery & Woodcraft',
    icon: 'Hammer',
    coverImage: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=1000&q=80',
    memberCount: 64,
    onlineCount: 11,
    tags: ['Kanna Planes', 'Nokogiri Saws', 'Glueless Joinery', 'Sharpening'],
    pinnedAnnouncement: '📌 Tool Care: Oil your carbon steel blades with camellia oil during humid seasons!',
    lastMessageSnippet: 'Cut a snug Kanawa-tsugi joint on hinoki cypress. Friction holds it like rock.',
    lastMessageTime: '2h ago',
    members: [
      {
        id: 'inst-hiro-tanaka',
        name: 'Hiro Tanaka',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
        role: 'mentor',
        status: 'idle',
        specialty: 'Master Carpenter',
      },
    ],
  },
];
