import { Course } from './types';

export const courses: Course[] = [
  {
    id: 'course-guitar-101',
    slug: 'neo-soul-guitar-mastery',
    title: 'Neo-Soul & Modern R&B Guitar Essentials',
    subtitle: 'Lush 9th chords, thumb-over basslines and velvety melodic fills',
    description: 'Break free from standard pentatonics. Learn the harmonic palette of contemporary neo-soul guitarists like Isaiah Sharkey, Melanie Faye, and Mateus Asato.',
    hobbyId: 'hobby-guitar',
    hobbyName: 'Electric Guitar & Tone',
    coverImage: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=1000&q=80',
    instructor: {
      id: 'inst-marcus-vance',
      name: 'Marcus Vance',
      title: 'Touring Guitarist & Session Musician',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
      bio: 'Over 12 years touring internationally and recording in Nashville & LA studios.',
      rating: 4.95,
      reviewCount: 382,
      studentsCount: 2410,
    },
    level: 'Intermediate',
    durationHours: 6.5,
    lessonsCount: 24,
    rating: 4.9,
    reviewCount: 318,
    studentCount: 1840,
    featured: true,
    trending: true,
    tags: ['Neo-Soul', 'Triads & 9ths', 'R&B Grooves', 'Tone Shaper'],
    modules: [
      {
        id: 'mod-g1',
        title: 'Module 1: Modern Chord Voicings & Inversions',
        lessons: [
          { id: 'les-g101', title: 'Drop 2 Chords & Extended Color Tones', durationMinutes: 18, isCompleted: true },
          { id: 'les-g102', title: 'Thumb-over Technique & Walking Basslines', durationMinutes: 22, isCompleted: true },
          { id: 'les-g103', title: 'Grace Notes, Hammer-ons & Micro-Slides', durationMinutes: 15, isCompleted: true },
        ],
      },
      {
        id: 'mod-g2',
        title: 'Module 2: Melodic Embellishments & Double Stops',
        lessons: [
          { id: 'les-g201', title: 'Connecting Voicings with 6th and 3rd Intervals', durationMinutes: 20, isCompleted: true },
          { id: 'les-g202', title: 'The Pentatonic Slip & Chromatic Approaches', durationMinutes: 25, isCompleted: false },
          { id: 'les-g203', title: 'Pocket Rhythm & Backbeat Ghost Strumming', durationMinutes: 19, isCompleted: false },
        ],
      },
      {
        id: 'mod-g3',
        title: 'Module 3: Analog Tone, Compressors & Spring Reverbs',
        lessons: [
          { id: 'les-g301', title: 'Dialing Low-Gain Transparent Overdrive', durationMinutes: 16, isCompleted: false },
          { id: 'les-g302', title: 'Pickup Selector Nuances & Tone Knob Magic', durationMinutes: 14, isCompleted: false },
        ],
      },
    ],
  },
  {
    id: 'course-coffee-101',
    slug: 'pourover-extraction-science',
    title: 'The Art of Pour-Over: Extraction & Sensory Science',
    subtitle: 'Dial in grind micron distribution, temperature curves and brew ratios',
    description: 'Master V60, Kalita Wave, and Origami drippers. Understand grind uniformity, dissolved solids (TDS), and unlocking fruity, floral notes in washed Ethiopian coffees.',
    hobbyId: 'hobby-coffee',
    hobbyName: 'Specialty Coffee Brewing',
    coverImage: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1000&q=80',
    instructor: {
      id: 'inst-elena-rostova',
      name: 'Elena Rostova',
      title: 'Q-Grader & World Brewers Cup Finalist',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
      bio: 'Specialty coffee consultant, certified SCA educator, and founder of Roam Roasters.',
      rating: 4.98,
      reviewCount: 460,
      studentsCount: 3120,
    },
    level: 'Beginner',
    durationHours: 4.2,
    lessonsCount: 16,
    rating: 4.95,
    reviewCount: 274,
    studentCount: 1420,
    featured: true,
    trending: false,
    tags: ['V60 Brewing', 'Grind Profiling', 'Sensory Tasting', 'Water Chemistry'],
    modules: [
      {
        id: 'mod-c1',
        title: 'Module 1: Water Chemistry & Bean Anatomy',
        lessons: [
          { id: 'les-c101', title: 'Mineral Content: Magnesium vs Calcium Balance', durationMinutes: 14, isCompleted: true },
          { id: 'les-c102', title: 'Processing Methods: Washed, Natural & Anaerobic', durationMinutes: 18, isCompleted: true },
        ],
      },
      {
        id: 'mod-c2',
        title: 'Module 2: Pour Mechanics & Flow Rate',
        lessons: [
          { id: 'les-c201', title: 'Bloom Agitation & Channeling Prevention', durationMinutes: 16, isCompleted: false },
          { id: 'les-c202', title: 'Center vs Spiral Pours on Flat-bottom vs Conical', durationMinutes: 20, isCompleted: false },
        ],
      },
    ],
  },
  {
    id: 'course-photo-101',
    slug: 'street-photography-mastery',
    title: 'Visual Storytelling: Street & Candid Composition',
    subtitle: 'Conquer the fear of shooting in public and frame raw urban narratives',
    description: 'Learn zone focusing, geometry, shadow play, and capturing authentic human moments in bustling city streets without intrusive gear.',
    hobbyId: 'hobby-photo',
    hobbyName: 'Street & Analog Photography',
    coverImage: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=1000&q=80',
    instructor: {
      id: 'inst-kai-takahashi',
      name: 'Kai Takahashi',
      title: 'Documentary Photographer & Leica Ambassador',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
      bio: 'Published in National Geographic and Monocle. Focused on Tokyo & NYC street cultures.',
      rating: 4.92,
      reviewCount: 520,
      studentsCount: 3950,
    },
    level: 'All Levels',
    durationHours: 5.8,
    lessonsCount: 20,
    rating: 4.88,
    reviewCount: 390,
    studentCount: 2210,
    featured: true,
    trending: true,
    tags: ['Street Geometry', 'Zone Focusing', '35mm Street', 'Light & Shadow'],
    modules: [
      {
        id: 'mod-p1',
        title: 'Module 1: Overcoming Street Anxiety & Approaching Subjects',
        lessons: [
          { id: 'les-p101', title: 'The Fishing Technique vs The Hunter Technique', durationMinutes: 22, isCompleted: true },
          { id: 'les-p102', title: 'Hyperfocal Distance & Rapid Zone Focusing', durationMinutes: 19, isCompleted: true },
        ],
      },
      {
        id: 'mod-p2',
        title: 'Module 2: Framing & Urban Geometry',
        lessons: [
          { id: 'les-p201', title: 'Leading Lines, Natural Frames & Reflections', durationMinutes: 24, isCompleted: false },
          { id: 'les-p202', title: 'Color Theory in Golden Hour & Neon Nightscapes', durationMinutes: 18, isCompleted: false },
        ],
      },
    ],
  },
  {
    id: 'course-pottery-101',
    slug: 'wheel-throwing-fundamentals',
    title: 'Wheel Throwing & Ceramic Form Mastery',
    subtitle: 'From centering 2kg clay to trimming delicate porcelain cups',
    description: 'A hands-on physical guide to centering, opening, pulling walls, wire cutting, trimming foot rings, and experimenting with natural ash glazes.',
    hobbyId: 'hobby-pottery',
    hobbyName: 'Studio Ceramic & Pottery',
    coverImage: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1000&q=80',
    instructor: {
      id: 'inst-clara-chen',
      name: 'Clara Chen',
      title: 'Ceramicist & Studio Potter',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
      bio: 'Runs a high-fire reduction pottery studio with bespoke pieces featured in Michelin star restaurants.',
      rating: 4.97,
      reviewCount: 289,
      studentsCount: 1650,
    },
    level: 'Beginner',
    durationHours: 7.0,
    lessonsCount: 28,
    rating: 4.93,
    reviewCount: 210,
    studentCount: 1180,
    featured: false,
    trending: true,
    tags: ['Wheel Throwing', 'Centering Clay', 'Foot Trimming', 'Studio Pottery'],
    modules: [
      {
        id: 'mod-po1',
        title: 'Module 1: Clay Preparation & Wheel Centering',
        lessons: [
          { id: 'les-po101', title: 'Wedging Techniques: Ram Head vs Spiral Wedging', durationMinutes: 17, isCompleted: true },
          { id: 'les-po102', title: 'Body Posture & Locking Your Elbows for Centering', durationMinutes: 25, isCompleted: false },
        ],
      },
    ],
  },
  {
    id: 'course-digital-art-101',
    slug: 'stylized-character-design',
    title: 'Stylized Character Design & Digital Painting',
    subtitle: 'Dynamic silhouettes, cinematic lighting & brushwork on iPad & Tablet',
    description: 'Transform rough thumbnail sketches into portfolio-ready character concepts with strong silhouette anatomy, vibrant color keys, and textural finishing.',
    hobbyId: 'hobby-digital-art',
    hobbyName: 'Digital Art & Concept Design',
    coverImage: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1000&q=80',
    instructor: {
      id: 'inst-sora-matsuda',
      name: 'Sora Matsuda',
      title: 'Lead Concept Artist @ Studio Orbit',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=300&q=80',
      bio: 'Veteran game concept artist and anime art director with 9+ years experience in Tokyo.',
      rating: 4.96,
      reviewCount: 680,
      studentsCount: 4800,
    },
    level: 'Intermediate',
    durationHours: 8.5,
    lessonsCount: 32,
    rating: 4.94,
    reviewCount: 512,
    studentCount: 3100,
    featured: true,
    trending: true,
    tags: ['Procreate', 'Character Design', 'Lighting Keys', 'Digital Brushwork'],
    modules: [
      {
        id: 'mod-da1',
        title: 'Module 1: Thumbnailing & Expressive Shape Language',
        lessons: [
          { id: 'les-da101', title: 'The Power of Shape Language: Circle, Square, Triangle', durationMinutes: 20, isCompleted: true },
          { id: 'les-da102', title: 'Gesture Line of Action & Asymmetry in Posing', durationMinutes: 24, isCompleted: true },
        ],
      },
    ],
  },
  {
    id: 'course-woodwork-101',
    slug: 'japanese-joinery-fundamentals',
    title: 'Traditional Japanese Woodworking: Hand Joints',
    subtitle: 'Chisel precision, mortise & tenon, and glueless wood craft',
    description: 'Discover the heritage of Japanese woodworking without screws or glue. Learn tool sharpening on waterstones, marking gauge precision, and cutting kanawa-tsugi joints.',
    hobbyId: 'hobby-woodwork',
    hobbyName: 'Japanese Joinery & Woodcraft',
    coverImage: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=1000&q=80',
    instructor: {
      id: 'inst-hiro-tanaka',
      name: 'Hiro Tanaka',
      title: 'Master Carpenter & Sashimono Craftsman',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
      bio: 'Third-generation wood artisan from Kyoto specializing in architectural joinery.',
      rating: 4.99,
      reviewCount: 340,
      studentsCount: 1980,
    },
    level: 'Masterclass',
    durationHours: 9.0,
    lessonsCount: 26,
    rating: 4.97,
    reviewCount: 280,
    studentCount: 1490,
    featured: false,
    trending: false,
    tags: ['Joinery', 'Japanese Planes', 'Waterstone Sharpening', 'Woodcraft'],
    modules: [
      {
        id: 'mod-w1',
        title: 'Module 1: Tool Tuning & Waterstone Sharpening',
        lessons: [
          { id: 'les-w101', title: 'Conditioning the Sole of a Kanna Hand Plane', durationMinutes: 26, isCompleted: false },
          { id: 'les-w102', title: 'Polishing Bevels on 1000/6000 Grit Waterstones', durationMinutes: 22, isCompleted: false },
        ],
      },
    ],
  },
];
