import { Hobby } from './types';

export const hobbies: Hobby[] = [
  {
    id: 'hobby-guitar',
    slug: 'electric-guitar',
    name: 'Electric Guitar & Tone',
    tagline: 'Master blues riffs, tube amp warmth & expressive lead bends',
    description: 'From neo-soul chord progressions to vintage analog pedalboard setups, explore tone craft and fretboard freedom.',
    category: 'Music & Sound',
    iconName: 'Guitar',
    coverImage: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1000&q=80',
    accentColor: '#FF5A36',
    studentCount: 3840,
    courseCount: 14,
    communityRoomsCount: 6,
    difficultyLevel: 'All Levels',
    popularTags: ['Tone Crafting', 'Blues Solos', 'Pedalboards', 'Neo-Soul'],
  },
  {
    id: 'hobby-coffee',
    slug: 'specialty-coffee',
    name: 'Specialty Coffee Brewing',
    tagline: 'Precision extraction, single-origin terroir & silky latte art',
    description: 'Unlock pour-over variables, espresso dial-in science, and tactile sensory tasting with world-class roasters.',
    category: 'Culinary Craft',
    iconName: 'Coffee',
    coverImage: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1000&q=80',
    accentColor: '#D97706',
    studentCount: 2950,
    courseCount: 9,
    communityRoomsCount: 4,
    difficultyLevel: 'Beginner Friendly',
    popularTags: ['Pour-Over', 'Espresso Dial-In', 'Latte Art', 'Aeropress'],
  },
  {
    id: 'hobby-photo',
    slug: 'street-photography',
    name: 'Street & Analog Photography',
    tagline: 'Decisive moments, golden hour framing & 35mm film magic',
    description: 'Capture human emotion, urban geometry, and atmospheric grain with manual camera mastery and street confidence.',
    category: 'Visual Arts',
    iconName: 'Camera',
    coverImage: 'https://images.unsplash.com/photo-1493863641943-9b68992a8d07?auto=format&fit=crop&w=1000&q=80',
    accentColor: '#0D9488',
    studentCount: 4120,
    courseCount: 16,
    communityRoomsCount: 8,
    difficultyLevel: 'Intermediate',
    popularTags: ['35mm Film', 'Composition', 'Street Portraits', 'Lightroom'],
  },
  {
    id: 'hobby-pottery',
    slug: 'clay-pottery',
    name: 'Studio Ceramic & Pottery',
    tagline: 'Tactile wheel throwing, earthy glazes & mindful hand-building',
    description: 'Center raw clay on the potter wheel, sculpt functional organic tableware, and master cone-6 reduction firing.',
    category: 'Tactile Crafts',
    iconName: 'Sparkles',
    coverImage: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1000&q=80',
    accentColor: '#E11D48',
    studentCount: 1890,
    courseCount: 8,
    communityRoomsCount: 3,
    difficultyLevel: 'Beginner Friendly',
    popularTags: ['Wheel Throwing', 'Glaze Chemistry', 'Hand-Building', 'Kiln Firing'],
  },
  {
    id: 'hobby-digital-art',
    slug: 'digital-illustration',
    name: 'Digital Art & Concept Design',
    tagline: 'Stylized character design, brushwork & cinematic lighting',
    description: 'Level up Procreate brush dynamics, dynamic anatomy, color keys, and modern isometric visual storytelling.',
    category: 'Design & Illustration',
    iconName: 'Palette',
    coverImage: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1000&q=80',
    accentColor: '#8B5CF6',
    studentCount: 5240,
    courseCount: 22,
    communityRoomsCount: 9,
    difficultyLevel: 'All Levels',
    popularTags: ['Procreate', 'Character Design', 'Color Keys', 'Visual Story'],
  },
  {
    id: 'hobby-woodwork',
    slug: 'japanese-joinery',
    name: 'Japanese Joinery & Woodcraft',
    tagline: 'Glueless interlocking joints, hand planes & cherry wood art',
    description: 'Experience meditative timber craft with razor-sharp kanna hand planes, nokogiri saws, and mortise-and-tenon joints.',
    category: 'Tactile Crafts',
    iconName: 'Hammer',
    coverImage: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=1000&q=80',
    accentColor: '#475569',
    studentCount: 1640,
    courseCount: 7,
    communityRoomsCount: 3,
    difficultyLevel: 'Intermediate',
    popularTags: ['Hand Planes', 'Interlocking Joints', 'Sashimono', 'Finishing'],
  },
];
