import { Quiz } from './types';

export const quizzes: Quiz[] = [
  {
    id: 'quiz-creative-spark',
    slug: 'find-your-creative-spark',
    title: 'Find Your Creative Spark',
    tagline: 'Discover the exact hobby that matches your mindset, rhythm, and free time',
    description: 'Answer 4 quick intuitive questions about how you unwind, what inspires you, and whether you prefer tactile, auditory, or visual expression.',
    estimatedMinutes: 3,
    coverImage: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1000&q=80',
    accentBadge: 'Most Popular',
    participantsCount: 8420,
    questions: [
      {
        id: 'q1',
        question: 'How do you prefer to unwind after a high-focus day?',
        description: 'Pick the scenario that gives you energy instead of draining it.',
        options: [
          {
            id: 'q1-a',
            label: 'Immersing in rich soundscapes & melodic chords',
            subtitle: 'Holding an instrument and losing track of time in rhythm',
            icon: 'Music',
            matchedHobbyIds: ['hobby-guitar'],
            matchedTraits: ['Auditory', 'Rhythm', 'Expressive'],
          },
          {
            id: 'q1-b',
            label: 'A meticulous sensory ritual with precise tools',
            subtitle: 'Measuring, brewing, weighing, and tasting subtle aromas',
            icon: 'Coffee',
            matchedHobbyIds: ['hobby-coffee'],
            matchedTraits: ['Sensory', 'Ritualistic', 'Precise'],
          },
          {
            id: 'q1-c',
            label: 'Wandering with eyes wide open, noticing hidden city details',
            subtitle: 'Chasing shadows, architecture, and fleeting human expressions',
            icon: 'Camera',
            matchedHobbyIds: ['hobby-photo'],
            matchedTraits: ['Visual', 'Observational', 'Exploratory'],
          },
          {
            id: 'q1-d',
            label: 'Getting hands completely dirty with physical materials',
            subtitle: 'Shaping clay, carving wood, or feeling organic textures',
            icon: 'Sparkles',
            matchedHobbyIds: ['hobby-pottery', 'hobby-woodwork'],
            matchedTraits: ['Tactile', 'Physical', 'Grounded'],
          },
        ],
      },
      {
        id: 'q2',
        question: 'What kind of satisfaction feels most rewarding to you?',
        description: 'Choose your preferred sense of accomplishment.',
        options: [
          {
            id: 'q2-a',
            label: 'A tangible physical object you can use every single day',
            subtitle: 'A ceramic mug, wooden dovetail box, or espresso drink',
            icon: 'PackageCheck',
            matchedHobbyIds: ['hobby-pottery', 'hobby-coffee', 'hobby-woodwork'],
            matchedTraits: ['Functional', 'Physical'],
          },
          {
            id: 'q2-b',
            label: 'A fleeting artistic moment captured for posterity',
            subtitle: 'A single high-contrast photo or an expressive guitar solo',
            icon: 'Film',
            matchedHobbyIds: ['hobby-photo', 'hobby-guitar'],
            matchedTraits: ['Ephemeral', 'Artistic'],
          },
          {
            id: 'q2-c',
            label: 'A digital visual world brought completely to life',
            subtitle: 'Character sketches, rich color palettes, and stylized concepts',
            icon: 'Palette',
            matchedHobbyIds: ['hobby-digital-art'],
            matchedTraits: ['Digital', 'World-building'],
          },
        ],
      },
      {
        id: 'q3',
        question: 'What is your ideal practice session environment?',
        description: 'Your sacred creative space.',
        options: [
          {
            id: 'q3-a',
            label: 'Late night desk corner with headphones & soft mood lighting',
            subtitle: 'Quiet personal flow state with no outside distractions',
            icon: 'Moon',
            matchedHobbyIds: ['hobby-guitar', 'hobby-digital-art'],
            matchedTraits: ['Solo', 'Nocturnal', 'Focus'],
          },
          {
            id: 'q3-b',
            label: 'Crisp morning kitchen with sunlight and steaming water',
            subtitle: 'Calm morning ritual to calibrate the senses',
            icon: 'SunMedium',
            matchedHobbyIds: ['hobby-coffee'],
            matchedTraits: ['Morning', 'Ritual', 'Sensory'],
          },
          {
            id: 'q3-c',
            label: 'Outdoors in the bustling urban rhythm of city avenues',
            subtitle: 'Dynamic environment with unpredictability and vitality',
            icon: 'MapPin',
            matchedHobbyIds: ['hobby-photo'],
            matchedTraits: ['Urban', 'Outdoors', 'Spontaneous'],
          },
          {
            id: 'q3-d',
            label: 'A studio or workshop with apron, dust, and raw materials',
            subtitle: 'Physical workspace where making a mess is part of the process',
            icon: 'Wrench',
            matchedHobbyIds: ['hobby-pottery', 'hobby-woodwork'],
            matchedTraits: ['Workshop', 'Hands-on'],
          },
        ],
      },
      {
        id: 'q4',
        question: 'How much time do you want to invest each week?',
        description: 'Be realistic about your current schedule.',
        options: [
          {
            id: 'q4-a',
            label: '15 to 30 minutes of daily micro-sessions',
            subtitle: 'Quick daily finger exercises, pour-overs, or sketch prompts',
            icon: 'Clock',
            matchedHobbyIds: ['hobby-guitar', 'hobby-coffee'],
            matchedTraits: ['Micro-habit', 'Daily'],
          },
          {
            id: 'q4-b',
            label: 'A dedicated 2–3 hour deep weekend block',
            subtitle: 'Full immersion in a ceramic studio or street photo walk',
            icon: 'Calendar',
            matchedHobbyIds: ['hobby-pottery', 'hobby-photo', 'hobby-woodwork'],
            matchedTraits: ['Deep Work', 'Weekend'],
          },
        ],
      },
    ],
    possibleResults: {
      'hobby-guitar': {
        hobbyId: 'hobby-guitar',
        hobbyName: 'Electric Guitar & Tone Crafting',
        headline: 'Your Match: Neo-Soul & Electric Guitar',
        matchScorePercent: 96,
        summary: 'You gravitate toward auditory expression, dynamic rhythm, and late-night flow states. Electric guitar gives you immediate sonic feedback and endless room for expressive chord nuance.',
        starterCourseId: 'course-guitar-101',
        recommendedBuddyRoomId: 'room-vintage-tone',
      },
      'hobby-coffee': {
        hobbyId: 'hobby-coffee',
        hobbyName: 'Specialty Coffee & Extraction',
        headline: 'Your Match: Precision Specialty Coffee Brewing',
        matchScorePercent: 94,
        summary: 'You thrive on mindful rituals, tactile sensory feedback, and scientific repeatability. Exploring specialty origin profiles will elevate your mornings into an art form.',
        starterCourseId: 'course-coffee-101',
        recommendedBuddyRoomId: 'room-aeropress',
      },
      'hobby-photo': {
        hobbyId: 'hobby-photo',
        hobbyName: 'Street & Analog Photography',
        headline: 'Your Match: Street Photography & Visual Storytelling',
        matchScorePercent: 92,
        summary: 'You are naturally observant, observant of hidden light, geometry, and human connection. Street photography turns every daily walk into a creative quest.',
        starterCourseId: 'course-photo-101',
        recommendedBuddyRoomId: 'room-leica-street',
      },
      'hobby-pottery': {
        hobbyId: 'hobby-pottery',
        hobbyName: 'Studio Ceramic & Clay Pottery',
        headline: 'Your Match: Studio Ceramic & Wheel Throwing',
        matchScorePercent: 95,
        summary: 'You need a tactile, screen-free outlet that connects mind and hands directly to earth materials. Pottery teaches centering, patience, and tangible craft.',
        starterCourseId: 'course-pottery-101',
        recommendedBuddyRoomId: 'room-ceramic-wheel',
      },
      'hobby-digital-art': {
        hobbyId: 'hobby-digital-art',
        hobbyName: 'Digital Art & Character Concept',
        headline: 'Your Match: Stylized Digital Concept Art',
        matchScorePercent: 91,
        summary: 'You love visual world-building, colors, and stylized illustration. Digital painting unlocks unlimited canvases and quick iterations.',
        starterCourseId: 'course-digital-art-101',
        recommendedBuddyRoomId: 'room-procreate-art',
      },
    },
  },
  {
    id: 'quiz-weekend-craft',
    slug: 'hands-on-weekend-craft',
    title: 'Which Hands-On Craft Suits Your Weekend?',
    tagline: 'Step away from screens and create something physical with your hands',
    description: 'Find out whether clay ceramics, specialty barista craft, or woodworking aligns with your tactile creative impulses.',
    estimatedMinutes: 2,
    coverImage: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1000&q=80',
    accentBadge: 'Screen Detox',
    participantsCount: 4180,
    questions: [
      {
        id: 'q-w1',
        question: 'Which tactile sensation do you find most appealing?',
        options: [
          {
            id: 'q-w1-a',
            label: 'Cool, wet, spinning clay between your palms',
            icon: 'Sparkles',
            matchedHobbyIds: ['hobby-pottery'],
            matchedTraits: ['Clay', 'Centering'],
          },
          {
            id: 'q-w1-b',
            label: 'The scent of roasted coffee blossoms and hot steaming water',
            icon: 'Coffee',
            matchedHobbyIds: ['hobby-coffee'],
            matchedTraits: ['Sensory', 'Aromatics'],
          },
          {
            id: 'q-w1-c',
            label: 'Crisp aromatic wood shavings curling off a hand plane',
            icon: 'Hammer',
            matchedHobbyIds: ['hobby-woodwork'],
            matchedTraits: ['Wood', 'Precision'],
          },
        ],
      },
    ],
    possibleResults: {
      'hobby-pottery': {
        hobbyId: 'hobby-pottery',
        hobbyName: 'Studio Ceramic & Pottery',
        headline: 'Your Match: Clay Wheel Throwing',
        matchScorePercent: 97,
        summary: 'The mindful tactile experience of spinning clay will wash away digital fatigue and give you handmade ceramic pieces for your home.',
        starterCourseId: 'course-pottery-101',
        recommendedBuddyRoomId: 'room-ceramic-wheel',
      },
      'hobby-woodwork': {
        hobbyId: 'hobby-woodwork',
        hobbyName: 'Japanese Woodcraft',
        headline: 'Your Match: Japanese Wood Joinery',
        matchScorePercent: 93,
        summary: 'A meditative study in grain direction, razor edges, and interlocking wooden puzzle joints that last for generations.',
        starterCourseId: 'course-woodwork-101',
        recommendedBuddyRoomId: 'room-japan-joinery',
      },
    },
  },
];
