import { Quiz } from './types';

export const quizzes: Quiz[] = [
  {
    id: 'quiz-creative-spark',
    slug: 'find-your-creative-spark',
    title: 'Creative Flow Finder',
    tagline: 'Discover the exact hobby that matches your mindset, rhythm, and free time',
    description: 'Answer 4 quick intuitive questions about how you unwind, what inspires you, and whether you prefer tactile, auditory, or visual expression.',
    category: 'General',
    estimatedMinutes: 3,
    coverImage: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1000&q=80',
    accentBadge: 'Trending #1',
    participantsCount: 8420,
    questions: [
      {
        id: 'q1',
        question: 'How do you prefer to unwind after a high-focus day?',
        description: 'Pick the scenario that gives you energy instead of draining it.',
        options: [
          {
            id: 'q1-a',
            label: 'Immersing in rich soundscapes & melodic chords',
            subtitle: 'Holding an instrument and losing track of time in rhythm',
            icon: 'Music',
            matchedHobbyIds: ['hobby-guitar'],
            matchedTraits: ['Auditory', 'Rhythm', 'Expressive'],
          },
          {
            id: 'q1-b',
            label: 'A meticulous sensory ritual with precise tools',
            subtitle: 'Measuring, brewing, weighing, and tasting subtle aromas',
            icon: 'Coffee',
            matchedHobbyIds: ['hobby-coffee'],
            matchedTraits: ['Sensory', 'Ritualistic', 'Precise'],
          },
          {
            id: 'q1-c',
            label: 'Wandering with eyes wide open, noticing hidden city details',
            subtitle: 'Chasing shadows, architecture, and fleeting human expressions',
            icon: 'Camera',
            matchedHobbyIds: ['hobby-photo'],
            matchedTraits: ['Visual', 'Observational', 'Exploratory'],
          },
          {
            id: 'q1-d',
            label: 'Getting hands completely dirty with physical materials',
            subtitle: 'Shaping clay, carving wood, or feeling organic textures',
            icon: 'Sparkles',
            matchedHobbyIds: ['hobby-pottery', 'hobby-woodwork'],
            matchedTraits: ['Tactile', 'Physical', 'Grounded'],
          },
        ],
      },
      {
        id: 'q2',
        question: 'What kind of satisfaction feels most rewarding to you?',
        description: 'Choose your preferred sense of accomplishment.',
        options: [
          {
            id: 'q2-a',
            label: 'A tangible physical object you can use every single day',
            subtitle: 'A ceramic mug, wooden dovetail box, or espresso drink',
            icon: 'PackageCheck',
            matchedHobbyIds: ['hobby-pottery', 'hobby-coffee', 'hobby-woodwork'],
            matchedTraits: ['Functional', 'Physical'],
          },
          {
            id: 'q2-b',
            label: 'A fleeting artistic moment captured for posterity',
            subtitle: 'A single high-contrast photo or an expressive guitar solo',
            icon: 'Film',
            matchedHobbyIds: ['hobby-photo', 'hobby-guitar'],
            matchedTraits: ['Ephemeral', 'Artistic'],
          },
          {
            id: 'q2-c',
            label: 'A digital visual world brought completely to life',
            subtitle: 'Character sketches, rich color palettes, and stylized concepts',
            icon: 'Palette',
            matchedHobbyIds: ['hobby-digital-art'],
            matchedTraits: ['Digital', 'World-building'],
          },
        ],
      },
      {
        id: 'q3',
        question: 'What is your ideal practice session environment?',
        description: 'Your sacred creative space.',
        options: [
          {
            id: 'q3-a',
            label: 'Late night desk corner with headphones & soft mood lighting',
            subtitle: 'Quiet personal flow state with no outside distractions',
            icon: 'Moon',
            matchedHobbyIds: ['hobby-guitar', 'hobby-digital-art'],
            matchedTraits: ['Solo', 'Nocturnal', 'Focus'],
          },
          {
            id: 'q3-b',
            label: 'Crisp morning kitchen with sunlight and steaming water',
            subtitle: 'Calm morning ritual to calibrate the senses',
            icon: 'SunMedium',
            matchedHobbyIds: ['hobby-coffee'],
            matchedTraits: ['Morning', 'Ritual', 'Sensory'],
          },
          {
            id: 'q3-c',
            label: 'Outdoors in the bustling urban rhythm of city avenues',
            subtitle: 'Dynamic environment with unpredictability and vitality',
            icon: 'MapPin',
            matchedHobbyIds: ['hobby-photo'],
            matchedTraits: ['Urban', 'Outdoors', 'Spontaneous'],
          },
          {
            id: 'q3-d',
            label: 'A studio or workshop with apron, dust, and raw materials',
            subtitle: 'Physical workspace where making a mess is part of the process',
            icon: 'Wrench',
            matchedHobbyIds: ['hobby-pottery', 'hobby-woodwork'],
            matchedTraits: ['Workshop', 'Hands-on'],
          },
        ],
      },
      {
        id: 'q4',
        question: 'How much time do you want to invest each week?',
        description: 'Be realistic about your current schedule.',
        options: [
          {
            id: 'q4-a',
            label: '15 to 30 minutes of daily micro-sessions',
            subtitle: 'Quick daily finger exercises, pour-overs, or sketch prompts',
            icon: 'Clock',
            matchedHobbyIds: ['hobby-guitar', 'hobby-coffee'],
            matchedTraits: ['Micro-habit', 'Daily'],
          },
          {
            id: 'q4-b',
            label: 'A dedicated 2–3 hour deep weekend block',
            subtitle: 'Full immersion in a ceramic studio or street photo walk',
            icon: 'Calendar',
            matchedHobbyIds: ['hobby-pottery', 'hobby-photo', 'hobby-woodwork'],
            matchedTraits: ['Deep Work', 'Weekend'],
          },
        ],
      },
    ],
    possibleResults: {
      'hobby-guitar': {
        hobbyId: 'hobby-guitar',
        hobbyName: 'Electric Guitar & Tone Crafting',
        headline: 'Your Match: Neo-Soul & Electric Guitar',
        matchScorePercent: 96,
        summary: 'You gravitate toward auditory expression, dynamic rhythm, and late-night flow states. Electric guitar gives you immediate sonic feedback and endless room for expressive chord nuance.',
        starterCourseId: 'course-guitar-101',
        recommendedBuddyRoomId: 'room-vintage-tone',
      },
      'hobby-coffee': {
        hobbyId: 'hobby-coffee',
        hobbyName: 'Specialty Coffee & Extraction',
        headline: 'Your Match: Precision Specialty Coffee Brewing',
        matchScorePercent: 94,
        summary: 'You thrive on mindful rituals, tactile sensory feedback, and scientific repeatability. Exploring specialty origin profiles will elevate your mornings into an art form.',
        starterCourseId: 'course-coffee-101',
        recommendedBuddyRoomId: 'room-aeropress',
      },
      'hobby-photo': {
        hobbyId: 'hobby-photo',
        hobbyName: 'Street & Analog Photography',
        headline: 'Your Match: Street Photography & Visual Storytelling',
        matchScorePercent: 92,
        summary: 'You are naturally observant of hidden light, geometry, and human connection. Street photography turns every daily walk into a creative quest.',
        starterCourseId: 'course-photo-101',
        recommendedBuddyRoomId: 'room-leica-street',
      },
      'hobby-pottery': {
        hobbyId: 'hobby-pottery',
        hobbyName: 'Studio Ceramic & Clay Pottery',
        headline: 'Your Match: Studio Ceramic & Wheel Throwing',
        matchScorePercent: 95,
        summary: 'You need a tactile, screen-free outlet that connects mind and hands directly to earth materials. Pottery teaches centering, patience, and tangible craft.',
        starterCourseId: 'course-pottery-101',
        recommendedBuddyRoomId: 'room-ceramic-wheel',
      },
      'hobby-digital-art': {
        hobbyId: 'hobby-digital-art',
        hobbyName: 'Digital Art & Character Concept',
        headline: 'Your Match: Stylized Digital Concept Art',
        matchScorePercent: 91,
        summary: 'You love visual world-building, colors, and stylized illustration. Digital painting unlocks unlimited canvases and quick iterations.',
        starterCourseId: 'course-digital-art-101',
        recommendedBuddyRoomId: 'room-procreate-art',
      },
    },
  },
  {
    id: 'quiz-sound-music',
    slug: 'sound-music-personality',
    title: 'Sound & Music Personality Test',
    tagline: 'Discover your sonic temperament, melodic ear, and ideal musical instrument',
    description: 'Explore what sonic vibrations resonate with your brain chemistry — from lush neo-soul fretboards to modular synthesis and acoustic fingerstyle.',
    category: 'Music & Audio',
    estimatedMinutes: 3,
    coverImage: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1000&q=80',
    accentBadge: 'New',
    participantsCount: 3240,
    questions: [
      {
        id: 'qm1',
        question: 'Which sound aesthetic makes the hairs on your neck stand up?',
        description: 'Trust your instinctual emotional reaction.',
        options: [
          {
            id: 'qm1-a',
            label: 'Velvety minor 9th chords on a warm tube amp',
            subtitle: 'Rich dynamics, expressive finger vibrato, and mellow overdrive',
            icon: 'Music',
            matchedHobbyIds: ['hobby-guitar'],
            matchedTraits: ['Harmony', 'Tube Tone', 'Expressive'],
          },
          {
            id: 'qm1-b',
            label: 'Raw organic street textures, laughter, and ambient city noise',
            subtitle: 'Field recordings and cinematic environmental soundscapes',
            icon: 'Radio',
            matchedHobbyIds: ['hobby-photo'],
            matchedTraits: ['Ambient', 'Observation', 'Cinematic'],
          },
          {
            id: 'qm1-c',
            label: 'Deep sub-bass grooves and syncopated hip-hop rhythms',
            subtitle: 'Punchy drum kicks, analog synthesizers, and lo-fi warmth',
            icon: 'Disc',
            matchedHobbyIds: ['hobby-guitar', 'hobby-digital-art'],
            matchedTraits: ['Groove', 'Electronic', 'Beatmaking'],
          },
        ],
      },
      {
        id: 'qm2',
        question: 'When learning a song, what part draws your attention first?',
        description: 'Your natural auditory filter.',
        options: [
          {
            id: 'qm2-a',
            label: 'The intricate chord progression and subtle voicings',
            subtitle: 'How chords transition and build emotional tension',
            icon: 'Sparkles',
            matchedHobbyIds: ['hobby-guitar'],
            matchedTraits: ['Theory', 'Nuance'],
          },
          {
            id: 'qm2-b',
            label: 'The visual atmosphere and story the song creates in your head',
            subtitle: 'Movie-like imagery, color mood, and pacing',
            icon: 'Palette',
            matchedHobbyIds: ['hobby-digital-art', 'hobby-photo'],
            matchedTraits: ['Visualizer', 'Imagination'],
          },
          {
            id: 'qm2-c',
            label: 'The rhythmic pocket and precision tempo',
            subtitle: 'Groove lock, syncopation, and micro-timing',
            icon: 'Zap',
            matchedHobbyIds: ['hobby-guitar', 'hobby-coffee'],
            matchedTraits: ['Rhythm', 'Precision'],
          },
        ],
      },
      {
        id: 'qm3',
        question: 'What is your ultimate musical milestone for this year?',
        description: 'Define your desired creative transformation.',
        options: [
          {
            id: 'qm3-a',
            label: 'Improvising fluidly over soul & jazz tracks without getting lost',
            subtitle: 'Unlocking fretboard freedom and muscle memory',
            icon: 'Flame',
            matchedHobbyIds: ['hobby-guitar'],
            matchedTraits: ['Improvisation', 'Fretboard Mastery'],
          },
          {
            id: 'qm3-b',
            label: 'Crafting the ultimate evening decompression playlist with live playing',
            subtitle: 'Playing for pure personal joy and inner peace',
            icon: 'Moon',
            matchedHobbyIds: ['hobby-guitar'],
            matchedTraits: ['Mindfulness', 'Decompression'],
          },
        ],
      },
    ],
    possibleResults: {
      'hobby-guitar': {
        hobbyId: 'hobby-guitar',
        hobbyName: 'Electric Guitar & Tone Crafting',
        headline: 'Your Match: Neo-Soul Electric Guitarist',
        matchScorePercent: 98,
        summary: 'Your musical ear is tuned to harmonic nuance, expressive dynamics, and soulful phrasing. Modern electric guitar essentials will give you immediate gratification and deep creative fulfillment.',
        starterCourseId: 'course-guitar-101',
        recommendedBuddyRoomId: 'room-vintage-tone',
      },
    },
  },
  {
    id: 'quiz-tactile-craft',
    slug: 'craft-tactile-affinity',
    title: 'Craft & Tactile Affinity Matrix',
    tagline: 'Feel the materials: Find which physical craft brings you into deep focus',
    description: 'Explore the balance between organic ceramic clay, fine precision woodcraft, and sensory barista chemistry.',
    category: 'Craft & Tactile',
    estimatedMinutes: 2,
    coverImage: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1000&q=80',
    accentBadge: 'Tactile Pick',
    participantsCount: 5120,
    questions: [
      {
        id: 'qt1',
        question: 'Which tactile sensation do you find most calming?',
        description: 'Choose what material you want between your fingers.',
        options: [
          {
            id: 'qt1-a',
            label: 'Cool, wet, spinning pottery clay smoothing under pressure',
            subtitle: 'Fluid organic shaping with instant physical feedback',
            icon: 'Sparkles',
            matchedHobbyIds: ['hobby-pottery'],
            matchedTraits: ['Fluid', 'Centering', 'Earthy'],
          },
          {
            id: 'qt1-b',
            label: 'Silky smooth aromatic cedar shavings off a razor hand plane',
            subtitle: 'Structural joinery, geometric cuts, and natural grain',
            icon: 'Hammer',
            matchedHobbyIds: ['hobby-woodwork'],
            matchedTraits: ['Structural', 'Aromatic', 'Precision'],
          },
          {
            id: 'qt1-c',
            label: 'Fresh ground coffee fragrance and silky microfoam texturing',
            subtitle: 'Thermal extraction, precise scales, and creamy latte art',
            icon: 'Coffee',
            matchedHobbyIds: ['hobby-coffee'],
            matchedTraits: ['Gastronomy', 'Aromas', 'Sensory'],
          },
        ],
      },
      {
        id: 'qt2',
        question: 'Where would you love to see your finished creation?',
        description: 'How you enjoy your craft output.',
        options: [
          {
            id: 'qt2-a',
            label: 'Sitting on your morning breakfast table as your favorite mug',
            subtitle: 'Used and cherished every day with warm tea or matcha',
            icon: 'Coffee',
            matchedHobbyIds: ['hobby-pottery'],
            matchedTraits: ['Daily Utility', 'Ceramics'],
          },
          {
            id: 'qt2-b',
            label: 'On your study desk as a hand-carved dovetail storage box',
            subtitle: 'Solid wood heirloom that lasts decades',
            icon: 'PackageCheck',
            matchedHobbyIds: ['hobby-woodwork'],
            matchedTraits: ['Heirloom', 'Durability'],
          },
        ],
      },
    ],
    possibleResults: {
      'hobby-pottery': {
        hobbyId: 'hobby-pottery',
        hobbyName: 'Studio Ceramic & Pottery',
        headline: 'Your Match: Wheel Throwing & Ceramics',
        matchScorePercent: 97,
        summary: 'The mindful tactile experience of spinning clay will wash away digital fatigue and give you handmade ceramic pieces for your home.',
        starterCourseId: 'course-pottery-101',
        recommendedBuddyRoomId: 'room-ceramic-wheel',
      },
      'hobby-woodwork': {
        hobbyId: 'hobby-woodwork',
        hobbyName: 'Japanese Woodcraft',
        headline: 'Your Match: Japanese Wood Joinery',
        matchScorePercent: 95,
        summary: 'A meditative study in grain direction, razor edges, and interlocking wooden puzzle joints that last for generations.',
        starterCourseId: 'course-woodwork-101',
        recommendedBuddyRoomId: 'room-japan-joinery',
      },
    },
  },
  {
    id: 'quiz-visual-lens',
    slug: 'visual-storyteller-lens',
    title: 'Visual Storyteller & Lens Match',
    tagline: 'Capture hidden perspectives through street lenses or digital canvases',
    description: 'Find out whether 35mm street photography or stylized Procreate digital painting matches your visual imagination.',
    category: 'Visual Arts',
    estimatedMinutes: 3,
    coverImage: 'https://images.unsplash.com/photo-1493863641943-9b68992a8d07?auto=format&fit=crop&w=1000&q=80',
    accentBadge: 'Visual Pick',
    participantsCount: 4680,
    questions: [
      {
        id: 'qv1',
        question: 'What catches your attention first when entering a new neighborhood?',
        description: 'Your instinctive visual radar.',
        options: [
          {
            id: 'qv1-a',
            label: 'Golden hour shadows cast between alleyways and passersby',
            subtitle: 'Fleeting moments of natural contrast and cinematic timing',
            icon: 'Camera',
            matchedHobbyIds: ['hobby-photo'],
            matchedTraits: ['Shadows', 'Street Life', 'Analog'],
          },
          {
            id: 'qv1-b',
            label: 'Vibrant neon palettes, stylized signage, and architectural lines',
            subtitle: 'Imagining how to illustrate and stylize the scene into concept art',
            icon: 'Palette',
            matchedHobbyIds: ['hobby-digital-art'],
            matchedTraits: ['Stylization', 'Color Theory', 'Illustration'],
          },
        ],
      },
      {
        id: 'qv2',
        question: 'Which creative tool feels more exhilarating?',
        description: 'Your preferred medium of creation.',
        options: [
          {
            id: 'qv2-a',
            label: 'A tactile rangefinder camera with a 35mm prime lens',
            subtitle: 'Framing real-world slices in fraction-of-a-second shutter clicks',
            icon: 'Eye',
            matchedHobbyIds: ['hobby-photo'],
            matchedTraits: ['Documentary', 'Shutter'],
          },
          {
            id: 'qv2-b',
            label: 'An Apple Pencil and pressure-sensitive digital canvas',
            subtitle: 'Unlimited color layers, custom brush textures, and zero mess',
            icon: 'PenTool',
            matchedHobbyIds: ['hobby-digital-art'],
            matchedTraits: ['Digital Canvas', 'Brushes'],
          },
        ],
      },
    ],
    possibleResults: {
      'hobby-photo': {
        hobbyId: 'hobby-photo',
        hobbyName: 'Street & Analog Photography',
        headline: 'Your Match: Street Photography & 35mm Film',
        matchScorePercent: 94,
        summary: 'You have a keen eye for light, dynamic composition, and authentic human moments. Street photography turns the entire world into your living museum.',
        starterCourseId: 'course-photo-101',
        recommendedBuddyRoomId: 'room-leica-street',
      },
      'hobby-digital-art': {
        hobbyId: 'hobby-digital-art',
        hobbyName: 'Digital Art & Character Concept',
        headline: 'Your Match: Digital Illustration & Concept Art',
        matchScorePercent: 93,
        summary: 'You are a visual world-builder. With digital illustration you can manifest entire universes, character designs, and luminous color palettes from thin air.',
        starterCourseId: 'course-digital-art-101',
        recommendedBuddyRoomId: 'room-procreate-art',
      },
    },
  },
  {
    id: 'quiz-weekend-maker',
    slug: 'weekend-maker-vibe',
    title: 'Weekend Maker Vibe: Screen Detox',
    tagline: 'Escape digital burnout with a weekend passion project',
    description: 'Find out whether brewing specialty roasts, pottery wheel throwing, or Japanese carpentry fits your free Saturday energy.',
    category: 'Weekend DIY',
    estimatedMinutes: 2,
    coverImage: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1000&q=80',
    accentBadge: 'Weekend Special',
    participantsCount: 6310,
    questions: [
      {
        id: 'qwm1',
        question: 'How do you want your weekend Saturday morning to feel?',
        description: 'Your dream creative weekend pace.',
        options: [
          {
            id: 'qwm1-a',
            label: 'Slow, aromatic, measuring Ethiopian coffee beans & dialing extraction',
            subtitle: 'Mindful peaceful sensory start with family or alone',
            icon: 'Coffee',
            matchedHobbyIds: ['hobby-coffee'],
            matchedTraits: ['Morning Ritual', 'Aromatics'],
          },
          {
            id: 'qwm1-b',
            label: 'Focused flow in a sunny pottery workshop with clay on your hands',
            subtitle: 'Immersive tactile clay shaping, trimming, and glazing',
            icon: 'Sparkles',
            matchedHobbyIds: ['hobby-pottery'],
            matchedTraits: ['Studio', 'Tactile'],
          },
          {
            id: 'qwm1-c',
            label: 'Measuring, chiseling, and fitting mortise & tenon joints in fragrant wood',
            subtitle: 'Building enduring furniture with hand tools',
            icon: 'Hammer',
            matchedHobbyIds: ['hobby-woodwork'],
            matchedTraits: ['Joinery', 'Handcraft'],
          },
        ],
      },
    ],
    possibleResults: {
      'hobby-coffee': {
        hobbyId: 'hobby-coffee',
        hobbyName: 'Specialty Coffee & Extraction',
        headline: 'Your Match: Specialty Barista & Pour-Over Ritual',
        matchScorePercent: 96,
        summary: 'Transform your weekend mornings into a sensory celebration. Master water temperature, grind distribution, and extraction science.',
        starterCourseId: 'course-coffee-101',
        recommendedBuddyRoomId: 'room-aeropress',
      },
      'hobby-pottery': {
        hobbyId: 'hobby-pottery',
        hobbyName: 'Studio Ceramic & Pottery',
        headline: 'Your Match: Wheel Throwing & Ceramics',
        matchScorePercent: 94,
        summary: 'The mindful tactile experience of spinning clay will wash away digital fatigue and give you handmade ceramic pieces for your home.',
        starterCourseId: 'course-pottery-101',
        recommendedBuddyRoomId: 'room-ceramic-wheel',
      },
      'hobby-woodwork': {
        hobbyId: 'hobby-woodwork',
        hobbyName: 'Japanese Woodcraft',
        headline: 'Your Match: Japanese Wood Joinery',
        matchScorePercent: 92,
        summary: 'A meditative study in grain direction, razor edges, and interlocking wooden puzzle joints that last for generations.',
        starterCourseId: 'course-woodwork-101',
        recommendedBuddyRoomId: 'room-japan-joinery',
      },
    },
  },
];
