import { SubscriptionPlan, MentorProfile } from './types';

export const subscriptionPlans: SubscriptionPlan[] = [
  {
    id: 'plan-starter',
    name: 'Explorer Tier',
    tagline: 'Perfect for self-paced hobby exploration and casual community jams',
    priceMonthly: 19,
    priceAnnualBilledMonthly: 14,
    popular: false,
    badge: 'Self-Paced',
    features: [
      'Unlimited access to all beginner & intermediate video courses',
      'Join all open Buddy Rooms & participate in weekly craft challenges',
      'Interactive quizzes & personalised hobby discovery roadmaps',
      'Daily streak tracking & community achievement badges',
      'Community discussion forums & peer review access',
    ],
    ctaLabel: 'Start Exploring',
    mentorshipCreditsPerMonth: 0,
  },
  {
    id: 'plan-pro',
    name: 'Pro Mentorship',
    tagline: 'Dedicated 1-on-1 mentor guidance, video feedback & fast craft growth',
    priceMonthly: 49,
    priceAnnualBilledMonthly: 39,
    popular: true,
    badge: 'Most Popular',
    features: [
      'Everything in Explorer Tier',
      '2 monthly 1-on-1 private video review sessions with verified mentors',
      'Asynchronous video feedback on your practice recordings within 24h',
      'Exclusive VIP Masterclass modules & raw project download files',
      'Private mentor direct messaging & feedback threads',
      'Priority access to limited-seat live workshops & studio hangouts',
    ],
    ctaLabel: 'Unlock Pro Mentorship',
    mentorshipCreditsPerMonth: 2,
  },
  {
    id: 'plan-master',
    name: 'Masterclass All-Access',
    tagline: 'The ultimate intensive for serious hobbyists aiming for professional mastery',
    priceMonthly: 99,
    priceAnnualBilledMonthly: 79,
    popular: false,
    badge: 'Intensive',
    features: [
      'Everything in Pro Mentorship Tier',
      '5 monthly 1-on-1 private coaching sessions with master artisans',
      'Personalised 90-day craft curriculum tailored to your specific goals',
      'Direct WhatsApp / Slack channel access to mentor inner circle',
      'Certificate of Studio Mastery upon module capstone review',
      'Free quarterly physical craft kit / curated bean samples shipped home',
    ],
    ctaLabel: 'Go All-Access',
    mentorshipCreditsPerMonth: 5,
  },
];

export const mentors: MentorProfile[] = [
  {
    id: 'inst-marcus-vance',
    name: 'Marcus Vance',
    handle: '@marcus_tone',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    coverImage: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1000&q=80',
    specialty: 'Neo-Soul, Funk Chords & Tone Architecture',
    hobbyId: 'hobby-guitar',
    hobbyName: 'Electric Guitar & Tone',
    bio: 'Session guitarist with 12+ years touring experience. I help guitarists move past generic pentatonics into expressive chord melody, thumb-over basslines, and analog pedalboard dynamics.',
    experienceYears: 12,
    rating: 4.95,
    reviewCount: 142,
    completedSessions: 380,
    hourlyRate: 65,
    availableNext: 'Tomorrow, 3:00 PM',
    skills: ['Neo-Soul Chords', 'Double-stops', 'Pedalboard Gain Staging', 'Fretboard Visualization'],
    featured: true,
    reviews: [
      {
        id: 'rev-m1',
        authorName: 'Alex Rivera',
        authorAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
        rating: 5,
        date: '3 days ago',
        comment: 'Marcus completely unlocked my thumb-over chord transition. In 45 minutes I learned what I was struggling with for 6 months on YouTube.',
      },
      {
        id: 'rev-m2',
        authorName: 'Saif B.',
        authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
        rating: 5,
        date: '1 week ago',
        comment: 'Incredible ear for tone. Helped me dial the sweet spot on my transparent overdrive and clean up fret noise.',
      },
    ],
  },
  {
    id: 'inst-elena-rostova',
    name: 'Elena Rostova',
    handle: '@elena_brews',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
    coverImage: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1000&q=80',
    specialty: 'Single-Origin Extraction & Sensory Calibration',
    hobbyId: 'hobby-coffee',
    hobbyName: 'Specialty Coffee Brewing',
    bio: 'Licensed Q-Grader and national brewer champion. We will analyze your grind distribution, water chemistry profile, and pour flow dynamics to consistently brew sweet, aromatic cups.',
    experienceYears: 9,
    rating: 4.98,
    reviewCount: 188,
    completedSessions: 490,
    hourlyRate: 60,
    availableNext: 'Today, 6:00 PM',
    skills: ['Pour-Over Profiling', 'Espresso Dial-In', 'Water Remineralization', 'Sensory Cupping'],
    featured: true,
    reviews: [
      {
        id: 'rev-e1',
        authorName: 'Chloe Adams',
        authorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
        rating: 5,
        date: '2 days ago',
        comment: 'Adjusted my mineral recipe to 45ppm magnesium and my Ethiopian washed coffee tasted like liquid peach tea. Elena is a wizard!',
      },
    ],
  },
  {
    id: 'inst-kai-takahashi',
    name: 'Kai Takahashi',
    handle: '@kai_leica',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    coverImage: 'https://images.unsplash.com/photo-1493863641943-9b68992a8d07?auto=format&fit=crop&w=1000&q=80',
    specialty: '35mm Street Candid & Visual Narrative',
    hobbyId: 'hobby-photo',
    hobbyName: 'Street & Analog Photography',
    bio: 'Documentary photographer based in Tokyo. Let us review your contact sheets, master zone focusing, conquer public shooting hesitation, and sequence photo books.',
    experienceYears: 14,
    rating: 4.92,
    reviewCount: 210,
    completedSessions: 520,
    hourlyRate: 75,
    availableNext: 'Friday, 11:00 AM',
    skills: ['Zone Focusing', 'Street Candids', 'Contact Sheet Editing', 'Film Scanning'],
    featured: true,
    reviews: [
      {
        id: 'rev-k1',
        authorName: 'Jin Woo',
        authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
        rating: 5,
        date: 'Last week',
        comment: 'Kai gave ruthless but constructive feedback on my contact sheets. Taught me to shoot the background first and wait for the character to walk into the frame.',
      },
    ],
  },
  {
    id: 'inst-clara-chen',
    name: 'Clara Chen',
    handle: '@clara_pottery',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    coverImage: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1000&q=80',
    specialty: 'Wheel Throwing & Reduction Ash Glazes',
    hobbyId: 'hobby-pottery',
    hobbyName: 'Studio Ceramic & Pottery',
    bio: 'Studio potter crafting functional tableware. I assist students with posture lock, centering heavy clay lumps effortlessly, trimming graceful foot rings, and firing kilns.',
    experienceYears: 11,
    rating: 4.97,
    reviewCount: 96,
    completedSessions: 230,
    hourlyRate: 70,
    availableNext: 'Saturday, 1:00 PM',
    skills: ['Centering 3kg Clay', 'Trimming Foot Rings', 'Ash Glaze Mixing', 'Teaware Ergonomics'],
    featured: false,
    reviews: [
      {
        id: 'rev-c1',
        authorName: 'Maya Lin',
        authorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
        rating: 5,
        date: '5 days ago',
        comment: 'Clara watched my wheel posture over video and pinpointed why my walls were collapsing on pull 3. Immediate breakthrough!',
      },
    ],
  },
  {
    id: 'inst-sora-matsuda',
    name: 'Sora Matsuda',
    handle: '@sora_concept',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=300&q=80',
    coverImage: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1000&q=80',
    specialty: 'Stylized Character Concept & Lighting Keys',
    hobbyId: 'hobby-digital-art',
    hobbyName: 'Digital Art & Concept Design',
    bio: 'Lead concept artist with credits in top anime & gaming studios. 1-on-1 portfolio reviews, brush dynamic customization, and lighting anatomy paint-overs.',
    experienceYears: 10,
    rating: 4.96,
    reviewCount: 315,
    completedSessions: 640,
    hourlyRate: 85,
    availableNext: 'Thursday, 4:00 PM',
    skills: ['Procreate Paint-overs', 'Silhouette Design', 'Cinematic Light Keys', 'Portfolio Review'],
    featured: true,
    reviews: [
      {
        id: 'rev-s1',
        authorName: 'Maya Lin',
        authorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
        rating: 5,
        date: '1 week ago',
        comment: 'Sora did a live paint-over on my character illustration and the rim lighting transformation was mind-blowing.',
      },
    ],
  },
  {
    id: 'inst-hiro-tanaka',
    name: 'Hiro Tanaka',
    handle: '@hiro_sashimono',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    coverImage: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=1000&q=80',
    specialty: 'Traditional Japanese Joinery & Kanna Sharpening',
    hobbyId: 'hobby-woodwork',
    hobbyName: 'Japanese Joinery & Woodcraft',
    bio: 'Sashimono furniture craftsman. Guiding students in micro-bevel sharpening, hand plane sole conditioning, and hand-cut interlocking wood joinery.',
    experienceYears: 20,
    rating: 4.99,
    reviewCount: 160,
    completedSessions: 310,
    hourlyRate: 90,
    availableNext: 'Next Monday, 10:00 AM',
    skills: ['Kanna Setup', 'Waterstone Mirror Polish', 'Glueless Joinery', 'Grain Reading'],
    featured: false,
    reviews: [
      {
        id: 'rev-h1',
        authorName: 'Alex Rivera',
        authorAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
        rating: 5,
        date: '2 weeks ago',
        comment: 'Hiro-sensei showed me how 10 minutes on an 8000 grit stone makes the hand plane whisper through white oak like butter.',
      },
    ],
  },
];
