import { User, BadgeItem } from './types';

export const dummyBadges: BadgeItem[] = [
  {
    id: 'badge-14-streak',
    title: '14-Day Streak Master',
    description: 'Practiced your creative craft consistently for 14 straight days.',
    icon: 'Flame',
    unlockedAt: '2026-10-05',
    category: 'streak',
  },
  {
    id: 'badge-tone-shaper',
    title: 'Tone Crafter',
    description: 'Completed your first 10 guitar phrasing & pedalboard sessions.',
    icon: 'Sliders',
    unlockedAt: '2026-09-28',
    category: 'craft',
  },
  {
    id: 'badge-pour-over-pro',
    title: 'Golden Extraction Ratio',
    description: 'Brewed and logged 20 distinct single-origin pour-overs.',
    icon: 'Coffee',
    unlockedAt: '2026-09-14',
    category: 'craft',
  },
  {
    id: 'badge-buddy-helper',
    title: 'Community Pillar',
    description: 'Shared feedback on 15 peer project recordings in Buddy Rooms.',
    icon: 'HeartHandshake',
    unlockedAt: '2026-10-01',
    category: 'community',
  },
  {
    id: 'badge-curious-explorer',
    title: 'Renaissance Explorer',
    description: 'Explored 3 distinct creative hobby categories in one month.',
    icon: 'Compass',
    unlockedAt: '2026-08-30',
    category: 'mastery',
  },
];

export const currentUser: User = {
  id: 'user-saif',
  name: 'Saif B.',
  username: 'saif_crafts',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
  bio: 'Exploring neo-soul chord melody, V60 dialing, and urban street photography on weekends. Always searching for good tone.',
  role: 'student',
  isCurrentUser: true,
  streak: {
    currentDays: 14,
    bestDays: 28,
    freezeCount: 2,
    lastActiveDate: '2026-10-07',
    weeklyActivity: [
      { day: 'Mon', active: true, minutes: 45 },
      { day: 'Tue', active: true, minutes: 30 },
      { day: 'Wed', active: true, minutes: 60 },
      { day: 'Thu', active: true, minutes: 40 },
      { day: 'Fri', active: true, minutes: 50 },
      { day: 'Sat', active: true, minutes: 90 },
      { day: 'Sun', active: true, minutes: 35 },
    ],
  },
  stats: {
    points: 2450,
    completedCourses: 3,
    hoursPracticed: 48,
    communityRank: 'Top 5% Learner',
    projectsShared: 8,
  },
  enrolledCourses: [
    {
      courseId: 'course-guitar-101',
      progressPercent: 68,
      lastAccessedLesson: 'The Pentatonic Slip & Chromatic Approaches',
      lastAccessedDate: '2 hours ago',
      completedLessonsCount: 8,
      totalLessonsCount: 12,
      nextLessonTitle: 'Module 2: Pocket Rhythm & Backbeat Ghost Strumming',
    },
    {
      courseId: 'course-coffee-101',
      progressPercent: 45,
      lastAccessedLesson: 'Bloom Agitation & Channeling Prevention',
      lastAccessedDate: 'Yesterday',
      completedLessonsCount: 4,
      totalLessonsCount: 8,
      nextLessonTitle: 'Module 2: Center vs Spiral Pours on Flat-bottom vs Conical',
    },
    {
      courseId: 'course-photo-101',
      progressPercent: 82,
      lastAccessedLesson: 'Leading Lines, Natural Frames & Reflections',
      lastAccessedDate: '3 days ago',
      completedLessonsCount: 8,
      totalLessonsCount: 10,
      nextLessonTitle: 'Module 2: Color Theory in Golden Hour & Neon Nightscapes',
    },
  ],
  interests: ['Electric Guitar', 'Specialty Coffee', 'Street Photography', 'Analog Tone', 'Ceramics'],
  badges: dummyBadges,
  bookmarkedCourseIds: ['course-digital-art-101', 'course-woodwork-101'],
};

export const peerUsers: User[] = [
  {
    id: 'user-maya',
    name: 'Maya Lin',
    username: 'mayapaints',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    bio: 'Digital illustrator & ceramic hobbyist. Big fan of pastel palettes and wheel thrown matcha bowls.',
    role: 'student',
    streak: {
      currentDays: 9,
      bestDays: 21,
      freezeCount: 1,
      lastActiveDate: '2026-10-07',
      weeklyActivity: [],
    },
    stats: {
      points: 1890,
      completedCourses: 2,
      hoursPracticed: 34,
      communityRank: 'Active Crafter',
      projectsShared: 12,
    },
    enrolledCourses: [],
    interests: ['Digital Art', 'Clay Pottery'],
    badges: [dummyBadges[0], dummyBadges[3]],
    bookmarkedCourseIds: [],
  },
  {
    id: 'user-alex',
    name: 'Alex Rivera',
    username: 'alex_fretboard',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
    bio: 'Stratocaster & tube amps junkie. Chasing Hendrix & Tom Misch chord voicing.',
    role: 'student',
    streak: {
      currentDays: 22,
      bestDays: 35,
      freezeCount: 0,
      lastActiveDate: '2026-10-07',
      weeklyActivity: [],
    },
    stats: {
      points: 3200,
      completedCourses: 4,
      hoursPracticed: 72,
      communityRank: 'Top 1% Musician',
      projectsShared: 19,
    },
    enrolledCourses: [],
    interests: ['Electric Guitar', 'Analog Tone'],
    badges: [dummyBadges[0], dummyBadges[1], dummyBadges[3]],
    bookmarkedCourseIds: [],
  },
  {
    id: 'user-chloe',
    name: 'Chloe Adams',
    username: 'chloe_extracts',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
    bio: 'Home barista geek. Current obsession: Geisha anaerobic natural brews on Kono drippers.',
    role: 'student',
    streak: {
      currentDays: 16,
      bestDays: 20,
      freezeCount: 2,
      lastActiveDate: '2026-10-06',
      weeklyActivity: [],
    },
    stats: {
      points: 2150,
      completedCourses: 2,
      hoursPracticed: 41,
      communityRank: 'Master Brewer',
      projectsShared: 6,
    },
    enrolledCourses: [],
    interests: ['Specialty Coffee', 'Water Chemistry'],
    badges: [dummyBadges[2], dummyBadges[0]],
    bookmarkedCourseIds: [],
  },
  {
    id: 'user-jin',
    name: 'Jin Woo',
    username: 'jin_leica',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    bio: 'Shooting black and white street scenes on Tri-X 400. Documenting rain in Seoul.',
    role: 'student',
    streak: {
      currentDays: 5,
      bestDays: 18,
      freezeCount: 3,
      lastActiveDate: '2026-10-07',
      weeklyActivity: [],
    },
    stats: {
      points: 1450,
      completedCourses: 1,
      hoursPracticed: 26,
      communityRank: 'Film Enthusiast',
      projectsShared: 15,
    },
    enrolledCourses: [],
    interests: ['Street Photography', 'Analog Film'],
    badges: [dummyBadges[3]],
    bookmarkedCourseIds: [],
  },
];
